# 有梯度跟踪


In [33]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

print(w)
print(b)
print(z)
print(loss)

print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

tensor([[-1.3463, -1.1899,  0.9205],
        [-2.1797,  0.1907,  0.2706],
        [ 0.2583, -2.0951, -0.2117],
        [-0.3301,  1.0219, -1.0481],
        [ 1.2303,  0.6093,  0.0857]], requires_grad=True)
tensor([-0.3662, -0.9586,  0.0565], requires_grad=True)
tensor([-2.7337, -2.4217,  0.0735], grad_fn=<AddBackward0>)
tensor(0.2929, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Gradient function for z = <AddBackward0 object at 0x000002CE70C85FF0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000002CE70C85FF0>


In [34]:
loss.backward()
print(w.grad)
print(b.grad)


result = torch.mm(x.view(1, -1), w) + b
print(f"result=")
print(result)
print(f"y=")
print(y)
## 性能一般

tensor([[0.0203, 0.0272, 0.1728],
        [0.0203, 0.0272, 0.1728],
        [0.0203, 0.0272, 0.1728],
        [0.0203, 0.0272, 0.1728],
        [0.0203, 0.0272, 0.1728]])
tensor([0.0203, 0.0272, 0.1728])
result=
tensor([[-2.7337, -2.4217,  0.0735]], grad_fn=<AddBackward0>)
y=
tensor([0., 0., 0.])


# 无梯度跟踪

In [35]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False
